# Numpy
- Numpy is a general-purpose array-processing package. 
- It provides a high-performance multidimensional array object, and tools for working with these arrays. 

In [73]:
import numpy as np

- use conda to install the library if numpy not already installed

# Array
- Array is a data structure that stores values of same data type. 
- Python lists can contain values corresponding to differeant data types, arrays in python can only contain values corresponding to same data type.
- Though list can completely replace array still we use arrays in ML cause operation on arrays are very fast than the list.

## Creating an Array
Converting a list to an array using array() method of numpy.

In [74]:
a=[1,2,3] # a list
print(a)
arr=np.array(a) # converting list to an array(Similar data type only)
print(arr)
#a = np.array([1, 2, 3]) --> Another short way to initialise array

[1, 2, 3]
[1 2 3]


In [75]:
a=[1,2,3,3.3] # int + float
print(a)
arr=np.array(a) # all elements of array to be float only
print(arr)

[1, 2, 3, 3.3]
[1.  2.  3.  3.3]


In [76]:
a=[1,2,3,False] # int + boolean
print(a)
arr=np.array(a) # all elements of array to be int only
print(arr)

[1, 2, 3, False]
[1 2 3 0]


In [77]:
a=[1,2,3,False,"a"] # int + boolean + string
print(a)
arr=np.array(a) # all elements of array to be string only
print(arr)

[1, 2, 3, False, 'a']
['1' '2' '3' 'False' 'a']


In [78]:
arr.shape # (rows, columns) 

(5,)

## Multi-Dimensional Array

In [79]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
l3 = [7, 8, 9]
arr2d = np.array([l1,l2,l3,l1])
print(arr2d)
# arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [80]:
arr2d.shape

(4, 3)

## Slicing


In [81]:
arr=np.array([1,2,3,4,5,6,7,8])

In [82]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
arr[3]

4

In [84]:
arr[0:3]

array([1, 2, 3])

In [85]:
arr[3:]

array([4, 5, 6, 7, 8])

#### 2-D Slicing

In [86]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10,11,12]]) 
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [87]:
arr2d[1:3,1:]

array([[5, 6],
       [8, 9]])

## Copying the array

In [88]:
arr1=arr # arr1 is a reference to arr array
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
arr1[3:]=400
arr1

array([  1,   2,   3, 400, 400, 400, 400, 400])

In [90]:
arr

array([  1,   2,   3, 400, 400, 400, 400, 400])

you just created a reference of 'arr' array so if you bring any change in "arr1" your are gonna see those change in "arr" also.

In [91]:
arr1=np.copy(arr)
arr1

array([  1,   2,   3, 400, 400, 400, 400, 400])

In [92]:
arr1[2]=8
arr1

array([  1,   2,   8, 400, 400, 400, 400, 400])

In [93]:
arr

array([  1,   2,   3, 400, 400, 400, 400, 400])

## Common Methods on Array

In [94]:
arr = np.array([1, 2, 3, 4, 5]) 

In [95]:
total = np.sum(arr) # Sum of all elements: 15 
print(total)

15


In [96]:
mean = np.mean(arr) # Mean of elements: 3.0 
print(mean)

3.0


In [97]:
maximum = np.max(arr) #Maximum element:5 
print(maximum)

5


## Operations on Arrays

In [98]:
arr1 = np.array([1, 2, 3])  

arr2 = np.array([4, 5, 6])  

In [99]:
# Element-wise addition 

result = arr1 + arr2      # [5, 7, 9] 
print(result)

[5 7 9]


In [100]:
# Element-wise multiplication 

result = arr1 * arr2      # [4, 10, 18] 
print(result)

[ 4 10 18]


In [101]:
# Dot product of two arrays 

dot_product = np.dot(arr1, arr2)      # 32 
print(dot_product)

32


# ..............

#### Filtering the array elements out of main array

In [102]:
arr

array([1, 2, 3, 4, 5])

In [103]:
val=4
arr[arr<val]

array([1, 2, 3])

#### Creating an array in a range

In [104]:
arr=np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [105]:
arr=np.arange(0,12,step=2)
arr

array([ 0,  2,  4,  6,  8, 10])

##### Create an array of 3,4 dimension with Random values between 0-1

In [106]:
np.random.rand(3,4)

array([[0.658968  , 0.68840129, 0.91284162, 0.45270683],
       [0.70204443, 0.00899294, 0.94085108, 0.10645346],
       [0.30846612, 0.71657997, 0.22305588, 0.10464189]])

#### Creating array with initial element values 1

In [107]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])